// Copyright (c) 2023 Drew Robbins
// SPDX-License-Identifier: MIT
using RecipeGen.Models.Requests;

namespace RecipeGen.Models.Responses;

public class RecipeResponse
{
    /// <summary>
    /// A 32-digit hexadecimal string that represents the identifier for the Recipe.
    /// </summary>
    public string Id { get; internal set; } = Guid.NewGuid().ToString("N");
    /// <summary>
    /// The Recipe generated by the Generative AI model.
    /// </summary>
    public Recipe Recipe { get; set; } = null!;
    /// <summary>
    /// The request that was sent to the service included in the response for later retrieval.
    /// </summary>
    public RecipeRequest Request { get; set; } = null!;
    /// <summary>
    /// The error message if the Generative AI model failed to generate a Recipe.
    /// </summary>
    public string? ErrorMessage { get; set; } = null!;
    /// <summary>
    /// The metrics of the Generative AI model.
    /// </summary>
    public ModelMetrics Metrics { get; set; } = null!;
    /// <summary>
    /// Indicates whether the response has been liked.
    /// </summary>
    public bool Liked { get; set; }
    /// <summary>
    /// Indciates whether the response has been disliked.
    /// </summary>
    public bool Disliked { get; set; }
}
