{
 "title": "RecipeGen Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Past 24 Hours", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Recipes",
   "type": "stat",
   "description": "Recipes generated",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(rate(recipegen_recipecount_count[24h])) * 60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Total Completion Tokens",
   "type": "stat",
   "description": "Completion tokens",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(rate(recipegen_completiontokens_count[24h])) * 60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Total Likes",
   "type": "stat",
   "description": "Recipes generated",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(rate(recipegen_likedrecipes_count[24h])) * 60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Total Dislikes",
   "type": "stat",
   "description": "Recipes disliked",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "floor(sum(rate(recipegen_dislikedrecipes_count[24h])) * 60 * 60 * 24)"
    }
   ]
  },
  {
   "title": "Estimated Costs",
   "type": "stat",
   "description": "Costs based on tokens",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((rate(recipegen_completiontokens_count[24h])*0.002/1000) + (rate(recipegen_completiontokens_count[24h])*0.0015/1000)) * 60 * 60 * 24"
    }
   ]
  },
  {
   "title": "Total Prompt Tokens",
   "type": "stat",
   "description": "Prompt tokens",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(rate(recipegen_prompttokens_count[24h]) * 60 * 60 * 24))"
    }
   ]
  },
  { "title": "Averages Per Request (1 Hour)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Prompt Length ",
   "type": "stat",
   "description": "Average prompt length ",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(recipegen_promptlength_bytes[1h])) / sum(rate(recipegen_recipecount_count[1h]))"
    }
   ]
  },
  {
   "title": "Prompt Tokens ",
   "type": "stat",
   "description": "Average prompt tokens per recipe ",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(recipegen_prompttokens_count[1h])) / sum(rate(recipegen_recipecount_count[1h]))"
    }
   ]
  },
  {
   "title": "Recipe Length",
   "type": "stat",
   "description": "Average recipe length",
   "gridPos": { "h": 4, "w": 5, "x": 10, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(recipegen_recipelength_bytes[1h])) / sum(rate(recipegen_recipecount_count[1h]))"
    }
   ]
  },
  {
   "title": "Completion Tokens",
   "type": "stat",
   "description": "Average completion tokens per recipe ",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(recipegen_completiontokens_count[1h])) / sum(rate(recipegen_recipecount_count[1h]))"
    }
   ]
  },
  { "title": "Rates Per Minute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tokens ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(recipegen_completiontokens_count[1m]) + rate(recipegen_prompttokens_count[1m])"
    }
   ]
  },
  {
   "title": "Requests ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 15 },
   "targets": [
    {
     "expr": "rate(recipegen_recipecount_count[1m])"
    }
   ]
  },
  {
   "title": "Tokens Per Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 15 },
   "targets": [
    {
     "expr": "(rate(recipegen_completiontokens_count[1m]) + rate(recipegen_prompttokens_count[1m])) / rate(recipegen_recipecount_count[1m])"
    }
   ]
  },
  {
   "title": "Likes ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 15 },
   "targets": [
    {
     "expr": "sum by(language) (rate(recipegen_likedrecipes_count[1m]))"
    }
   ]
  },
  {
   "title": "Parse Errors ",
   "type": "timeseries",
   "description": "A response from AI was unable to be parsed",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(recipegen_recipeparseerror_count[1m])"
    }
   ]
  },
  {
   "title": "Elapsed Completion Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(rate(recipegen_recipetime_ms[1m]) / rate(recipegen_recipecount_count[1m]))/1000"
    }
   ]
  },
  {
   "title": "Dislikes ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 21 },
   "targets": [
    {
     "expr": "sum by(language) (rate(recipegen_dislikedrecipes_count[1m]))"
    }
   ]
  }
 ]
}