name: Node Lint and Test

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Install dependencies
      run: cd src/app && npm ci
    - name: Lint
      run: cd src/app && eslint --max-warnings 0 .
    - name: Test
      run: cd src/app && CI=true npm test -- --coverage
    - name: Archive coverage reports
      uses: actions/upload-artifact@v2
      with:
        name: react-coverage-report
        path: src/app/coverage/lcov-report
